# Generated by Django 2.2.16 on 2020-10-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201012_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.TextField(verbose_name='task_text'),
        ),
    ]
